name: "CLA Assistant"

on:
  issue_comment:
    types:
      - "created"
  pull_request:
    types:
      - "opened"
      - "closed"
      - "synchronize"

jobs:
  cla-assistant:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: "CLA Assistant"
        if: "(github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'"
        uses: "cla-assistant/github-action@v2.1.3-beta"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PERSONAL_ACCESS_TOKEN: "${{ secrets.PRO_ACCESS_TOKEN }}"
        with:
          remote-organization-name: "NishantBansal2003"
          remote-repository-name: "keploy"
          path-to-signatures: "etc/cla-signatures/signatures.json"
          path-to-document: "https://github.com/NishantBansal2003/keploy/blob/main/.github/CLA.md"
          branch: "cla-signatures"
          allowlist: "keploy-bot,renovate"

      - name: "Post Failure Instructions"
        if: failure()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "**The CLA check failed.** Please ensure you have:
          - Signed the CLA by commenting **'I have read the CLA Document and I hereby sign the CLA.'**
          - Used the correct email address in your commits (matches the one you used to sign the CLA).
          
          After fixing these issues, comment **'recheck'** to trigger the workflow again."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}